### ISSUE TITLE
Resend bitmasks

### ISSUE THREAD

**Issue by piot** [coherence/replication-server#102]

**Comment by tadej** [comment]
Server is now resending everything all the time without stopping (but doing it in priority at least)
Consumes a lot of bandwidth at the moment
When a packet is dropped, you need to check the components that were lost, and check if we sent it afterwards, otherwise resend; 
we should use an optimistic approach. Assume that a major part of the packets actually gets through.
Packet drops are not so frequent nowadays, assume it will not get dropped
Resend the current values, not the old ones
Use the versionID in ecs-go and instantiationID.
