### ISSUE TITLE
Commands broken

### ISSUE THREAD

**Issue by eriksvedang** [coherence/replication-server#195]
Release `v0.0.4-a26` of the server broke commands (at least how they used to work) on the client.

You used to be able to define a command in the schema and then do this in the client code:

```csharp
EntityManager.GetBuffer<DoitRequest>(entity);
```

This buffer would have been created by this schema-generated method:

```
        public static void CreateIfNeededAndReadComponentDataUpdate(EntityManager entityManager, Entity entity, uint componentType, AbsoluteSimulationFrame simulationFrame, IInBitStream bitStream, ILog log)
        {
#region Commands
            {
                var hasBuffer = entityManager.HasComponent<Doit>(entity);
                if (!hasBuffer)
                {
                    entityManager.AddBuffer<Doit>(entity);
                }
                var hasRequestBuffer = entityManager.HasComponent<DoitRequest>(entity);
                if (!hasRequestBuffer)
                {
                    entityManager.AddBuffer<DoitRequest>(entity);
                }
            }
#endregion
```

This method does not seem to be called anymore, due to changes around delta bitmasks.

**Comment by eriksvedang** [comment]
Note: The send queries are now in the ecs-query repo (they used to be in the replication-server)

**Comment by eriksvedang** [comment]
One workaround is to do this before sending commands:
```
                var hasRequestBuffer = EntityManager.HasComponent<DoitRequest>(entity);
                if (!hasRequestBuffer)
                {
                    EntityManager.AddBuffer<DoitRequest>(entity);
                }
```

This doesn't change the fact that a bunch of server logic for "Constructs" seem to have changed (and that the client has not adopted to this), but it makes commands work again.

They also send strings larger than 2 characters, as far as I can tell (re https://github.com/coherence/unity-sdk-runtime/issues/132)

**Comment by rpadrela** [comment]
I was reading through https://stagingdev.coherence.io/docs/unity/0.0.1/first_project_8_commands/ to learn more about commands but the doc seems to be outdated.

I'm presuming that calling
```
EntityManager.GetBuffer<DoitRequest>(entity)
```

replaces having to explicitly adding the buffer as `CreateIfNeededAndReadComponentDataUpdate()` is meant to be called but isn't and that's what the problem is, right?

**Comment by rpadrela** [comment]
> CreateIfNeededAndReadComponentDataUpdate

Ignore my comment above. I don't think it makes sense. `EntityManager.GetBuffer<DoitRequest>(entity)` is part of the `Entities` package so it couldn't possibly call our `CreateIfNeededAndReadComponentDataUpdate()`, unless of course, we were providing it as some form of callback, which I don't think is the case here.

**Comment by rpadrela** [comment]
`CreateIfNeededAndReadComponentDataUpdate()` does get called for me.

`DetectCommandsSentSystem` is what seems to convert `ApplyDamageRequest` into commands pushed into the `MessageChannels` which will then be serialised by the `Sender.Send()`. 

`DetectCommandsSentSystem` does not seem to be instantiated. I added an instance of it to the `CoherenceRuntimeSystem`. Added a `Tick()` method to `DetectCommandsSentSystem` which calls its own `OnUpdate()`. This is a bunch of scaffolding for testing. I wasn't able to understand why the `OnUpdate()` on the `DetectCommandsSentSystem` wasn't getting called once I created an instance of it.

Now, with the `DetectCommandsSentSystem.OnUpdate()` getting called we get commands pushed into the `MessageChannels` which are automatically serialised by the `Sender.Send()`. However, the server is crashing due to difference between serialisation and deserialisation logic. The server seems to be trying to deserialise a `SerializeEntityID` from data serialised by the client that doesn't look like a `SerializeEntityID`. Check `MessageQueueSerializer.SerializeQueue()` after it serialises the `prefixCommand` and the `count`. The server is reading both the `prefixCommand` and `count` correctly.

**Comment by rpadrela** [comment]
The Server is reading the following:

<img width="729" alt="Screenshot 2020-10-15 at 15 05 44" src="https://user-images.githubusercontent.com/1284234/96144722-63921e80-0efc-11eb-9603-54bf236426d6.png">

when the Client wrote what's in the `WriteFromStream()` method:

<img width="1548" alt="Screenshot 2020-10-15 at 15 35 11" src="https://user-images.githubusercontent.com/1284234/96144790-76a4ee80-0efc-11eb-86bd-6aa98cc5ced7.png">

It's not clear what the `WriteFromStream()` is actually writing.

**Comment by rpadrela** [comment]
The reason why serialization/deserialization logic is broken is because the client is making use of a DebugOutBitStream and the server is not.

**Comment by rpadrela** [comment]
Forcing instantiation of `DetectCommandsSentSystem` and its `OnUpdate()` to be called + removing the use of the DebugOutBitStream() on the client for commands serialisation fixes the issue with the ApplyDamage not being applied on the remote spaceship.

**Comment by rpadrela** [comment]
The reason why `DetectCommandsSentSystem` isn't automatically instantiated is because the class does not provide a default constructor.

**Comment by rpadrela** [comment]
PR with fixes: https://github.com/coherence/protocol-code-generator/pull/169
